const tailwind = require('tailwindcss/colors');
const { tailwindColors } = require('@churchtools/colors');

const safelistedColors = Object.keys(tailwindColors).flatMap((key) => [
    `bg-${key}-100`,
    `bg-${key}-500`,
    `text-${key}-100`,
    `text-${key}-500`,
    `text-${key}-900`,
]);

const moreSafelisted = [
    'amber',
    'blue',
    'green',
    'indigo',
    'red',
    'teal',
].flatMap((key) => [`border-${key}-200`, `text-${key}-300`]);

module.exports = {
    important: true,
    content: [
        './index.html',
        './src/**/*.{js,ts,vue}',
        './node_modules/@churchtools/styleguide/dist/churchtools-styleguide.es.js',
    ],
    safelist: [
        ...safelistedColors,
        ...moreSafelisted,
        'inline-flex',
        'px-3',
        'py-0.5',
        'rounded',
        'font-sans',
        'rounded-lg',
        'mb-1',
        'line-clamp-6',
    ],
    darkMode: 'class',
    corePlugins: {
        preflight: false,
    },
    theme: {
        borderRadius: {
            none: 0,
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.25rem',
            lg: '0.5rem',
            xl: '0.625rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.6875rem', '1rem'],
            sm: ['0.8125rem', '1.125rem'],
            base: ['0.875rem', '1.25rem'],
            lg: ['1.125rem', '1.625rem'],
            xl: ['1.25rem', '1.625rem'],
            '2xl': ['1.75rem', '2.125rem'],
            '3xl': ['2.375rem', '2.875rem'],
        },
        colors: {
            ...tailwindColors,
            black: tailwind.black,
            white: tailwind.white,
            transparent: tailwind.transparent,
            error: tailwindColors.red,
            warning: tailwindColors.yellow,
            success: tailwindColors.green,
        },
        extend: {
            colors: {
                primary: {
                    50: 'var(--primary-50)',
                    100: 'var(--primary-100)',
                    200: 'var(--primary-200)',
                    300: 'var(--primary-300)',
                    400: 'var(--primary-400)',
                    500: 'var(--primary-500)',
                    600: 'var(--primary-600)',
                    700: 'var(--primary-700)',
                    800: 'var(--primary-800)',
                    900: 'var(--primary-900)',
                    950: 'var(--primary-950)',
                },
            },
            spacing: {
                4.5: '1.125rem',
                13: '3.25rem',
                15: '3.75rem',
                17: '4.25rem',
                18: '4.5rem',
                19: '4.75rem',
            },
            maxWidth: {
                0: '0px',
                none: 'none',
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
                '2xl': '40rem',
                p: '43.75rem',
                content: '57.5rem',
            },
            fontFamily: {
                sans: [
                    'Lato',
                    'ui-sans-serif',
                    'system-ui',
                    '-apple-system',
                    'BlinkMacSystemFont',
                    '"Segoe UI"',
                    'Roboto',
                    '"Helvetica Neue"',
                    'Arial',
                    '"Noto Sans"',
                    'sans-serif',
                    '"Apple Color Emoji"',
                    '"Segoe UI Emoji"',
                    '"Segoe UI Symbol"',
                    '"Noto Color Emoji"',
                ],
            },
        },
    },
    plugins: [],
};
